// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductInventory.Infrastructure.Persistence;

#nullable disable

namespace ProductInventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918235955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductInventory.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100000L);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100001,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2.4GHz wireless mouse with USB receiver",
                            Name = "Wireless Mouse",
                            Price = 19.99m,
                            RowVersion = new byte[0],
                            Stock = 150
                        },
                        new
                        {
                            Id = 100002,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tenkeyless mechanical keyboard, blue switches",
                            Name = "Mechanical Keyboard",
                            Price = 79.99m,
                            RowVersion = new byte[0],
                            Stock = 75
                        },
                        new
                        {
                            Id = 100003,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "27-inch QHD IPS monitor, 144Hz",
                            Name = "27-inch Monitor",
                            Price = 299.00m,
                            RowVersion = new byte[0],
                            Stock = 30
                        },
                        new
                        {
                            Id = 100004,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "7-in-1 USB-C hub with HDMI and card reader",
                            Name = "USB-C Hub",
                            Price = 34.50m,
                            RowVersion = new byte[0],
                            Stock = 200
                        },
                        new
                        {
                            Id = 100005,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full HD webcam with built-in microphone",
                            Name = "Webcam 1080p",
                            Price = 45.00m,
                            RowVersion = new byte[0],
                            Stock = 0
                        },
                        new
                        {
                            Id = 100006,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aluminum adjustable laptop stand",
                            Name = "Laptop Stand",
                            Price = 29.99m,
                            RowVersion = new byte[0],
                            Stock = 120
                        },
                        new
                        {
                            Id = 100007,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Over-ear ANC headphones, 30h battery",
                            Name = "Noise Cancelling Headphones",
                            Price = 149.99m,
                            RowVersion = new byte[0],
                            Stock = 60
                        },
                        new
                        {
                            Id = 100008,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable USB 3.2 SSD, 1TB",
                            Name = "External SSD 1TB",
                            Price = 89.99m,
                            RowVersion = new byte[0],
                            Stock = 90
                        },
                        new
                        {
                            Id = 100009,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Extended desk mat, 900x400mm",
                            Name = "Desk Mat",
                            Price = 15.00m,
                            RowVersion = new byte[0],
                            Stock = 5
                        },
                        new
                        {
                            Id = 100010,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mesh-back ergonomic office chair",
                            Name = "Ergonomic Chair",
                            Price = 219.00m,
                            RowVersion = new byte[0],
                            Stock = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
